Settings:
  # 清理間隔（秒）
  cleanup-interval: 30
  # 最大緩存實體數
  max-recent-entries: 1000
  # 是否啟用效能監控
  enable-metrics: true
  # 異步處理超時（毫秒）
  async-timeout: 5000
  # 是否在控制台顯示調試信息
  debug: true
  # 效能指標檔案保留天數
  metrics-retention-days: 30  

ShowMessageInActionBar:
  Enabled: true #是否使用 ActionBar 發送訊息
  Message: '§7｜§6系統§7｜§f飯娘：§7您擊殺了 §e%mob% §7，故獲得了 §a%amount%乙太§f（ꆙ） §7獎勵！'

Mobs:
  Animals:
    # 預設值
    Min: 0.1 
    Max: 2
    DropChance: 5
    NumberOfDrops: 1
    OnlyOnKill: true
    # 特定生物
    ARMADILLO:
      Enabled: true #是否啟用
      Min: 0.1 #最少值
      Max: 2 #最大值
      DropChance: 5 #機率
      NumberOfDrops: 1 #會掉落幾份
      OnlyOnKill: true #限定玩家擊殺
    CHICKEN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PIG:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SHEEP:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    COW:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    MUSHROOM_COW:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PARROT:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SQUID:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    BAT:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    OCELOT:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    CAT:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PANDA:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    HORSE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SKELETON_HORSE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ZOMBIE_HORSE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    DONKEY:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    MULE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    LLAMA:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    TRADER_LLAMA:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    FOX:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    RABBIT:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    TURTLE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    POLAR_BEAR:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    COD:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SALMON:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PUFFERFISH:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    TROPICAL_FISH:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    DOLPHIN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    BEE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    WOLF:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SNOWMAN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    GOAT:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    GLOW_SQUID:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    AXOLOTL:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    TADPOLE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    FROG:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    CAMEL:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SNIFFER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
      
      
  HostileOverworld:
    Min: 0.1
    Max: 2
    DropChance: 5
    NumberOfDrops: 1
    OnlyOnKill: true
    BREEZE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    BOGGED:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ZOMBIE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ZOMBIE_VILLAGER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    DROWNED:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    HUSK:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    STRAY:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    GIANT:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SPIDER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    CAVE_SPIDER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SKELETON:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    GUARDIAN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ELDER_GUARDIAN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SLIME:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SILVERFISH:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    WITCH:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    CREEPER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PHANTOM:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true

  Villagers:
    Min: 0.1
    Max: 2
    DropChance: 5
    NumberOfDrops: 1
    OnlyOnKill: true
    VILLAGER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    WANDERING_TRADER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ALLAY:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    IRON_GOLEM:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    VINDICATOR:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    EVOKER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PILLAGER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    RAVAGER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    VEX:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true

  Nether:
    Min: 0.1
    Max: 2
    DropChance: 5
    NumberOfDrops: 1
    OnlyOnKill: true
    WITHER_SKELETON:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    STRIDER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    # This is old Zombie Pigman used for 1.15 and under
    PIG_ZOMBIE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PIGLIN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    PIGLIN_BRUTE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ZOMBIFIED_PIGLIN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    HOGLIN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ZOGLIN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    MAGMA_CUBE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    BLAZE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    GHAST:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true

  End:
    Min: 0.1
    Max: 2
    DropChance: 5
    NumberOfDrops: 1
    OnlyOnKill: true
    ENDERMAN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    ENDERMITE:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    SHULKER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true

  Bosses:
    Min: 0.1
    Max: 2
    DropChance: 5
    NumberOfDrops: 1
    OnlyOnKill: true
    ENDER_DRAGON:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    WITHER:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true
    WARDEN:
      Enabled: true
      Min: 0.1
      Max: 2
      DropChance: 5
      NumberOfDrops: 1
      OnlyOnKill: true